# **Import neccesary Libraries**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error , mean_squared_error , r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
print("Libraries Loaded")

Libraries Loaded

# **EDA**

## *Load The Data*

In [3]:
df = pd.read_csv("C:\\Users\\abhay\\OneDrive\\Desktop\\ML learning\\Linear Regression\\Student Score\\Data\\student_scores.csv")

## *Exploration*

In [5]:
# Data shape
df.shape

(528, 7)

In [4]:
# First 5 Rows
df.head()

   study_hours_per_day  attendance_percent  ...  assignments_completed  exam_score
0                  0.2                75.0  ...                    3.0        66.4
1                  0.6                77.6  ...                   11.0        91.4
2                  0.5                69.1  ...                   18.0        84.3
3                  9.1                73.7  ...                    1.0       100.0
4                  7.2                36.8  ...                    1.0       100.0

[5 rows x 7 columns]

In [6]:
# last Five Rows
df.tail()

     study_hours_per_day  attendance_percent  ...  assignments_completed  exam_score
523                  1.3                86.8  ...                    3.0        57.8
524                  0.8                33.5  ...                   15.0        76.6
525                  3.4                48.8  ...                   18.0        85.8
526                  4.2                82.2  ...                   19.0       100.0
527                  3.9                75.1  ...                    3.0        91.4

[5 rows x 7 columns]

In [7]:
# The Data Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 528 entries, 0 to 527
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours_per_day    513 non-null    float64
 1   attendance_percent     528 non-null    float64
 2   sleep_hours            508 non-null    float64
 3   previous_score         528 non-null    float64
 4   has_tuition            528 non-null    float64
 5   assignments_completed  528 non-null    float64
 6   exam_score             528 non-null    float64
dtypes: float64(7)
memory usage: 29.0 KB

In [10]:
df.describe()

       study_hours_per_day  ...  exam_score
count           513.000000  ...  528.000000
mean              4.919103  ...   88.799242
std               2.905744  ...   14.505556
min               0.000000  ...  -20.000000
25%               2.500000  ...   80.200000
50%               4.900000  ...   92.850000
75%               7.500000  ...  100.000000
max              10.000000  ...  200.000000

[8 rows x 7 columns]

In [11]:
# NaN Values
df.isna().sum()

study_hours_per_day      15
attendance_percent        0
sleep_hours              20
previous_score            0
has_tuition               0
assignments_completed     0
exam_score                0
dtype: int64

In [ ]:
# Duplicated values
df.duplicated().sum()

np.int64(8)

# **Data Cleaning**

In [35]:
df_copy = df.copy()

## *Impossible values*

In [ ]:
df_copy.loc[df_copy['exam_score']<0,'exam_score'] = np.nan
df_copy.loc[df_copy['exam_score']>100,'exam_score'] = np.nan
df_copy.loc[df_copy['attendance_percent']>100,'attendance_percent'] = np.nan

## *Fill NaN*

In [51]:
print("NaN values Before:- \n")
print(df_copy.isna().sum())

print("\nNaN values after:-\n")
df_copy['study_hours_per_day'] = df_copy['study_hours_per_day'].fillna(df_copy['study_hours_per_day'].median())
df_copy['attendance_percent'] = df_copy['attendance_percent'].fillna(df_copy['attendance_percent'].median())
df_copy['sleep_hours'] = df_copy['sleep_hours'].fillna(df_copy['sleep_hours'].median())
df_copy['exam_score'] = df_copy['exam_score'].fillna(df_copy['exam_score'].median())
print(df_copy.isna().sum())

NaN values Before:-

study_hours_per_day      15
attendance_percent        1
sleep_hours              20
previous_score            0
has_tuition               0
assignments_completed     0
exam_score                2
dtype: int64

NaN values after:-

study_hours_per_day      0
attendance_percent       0
sleep_hours              0
previous_score           0
has_tuition              0
assignments_completed    0
exam_score               0
dtype: int64

## *Drop Duplicates*

In [54]:
print(f"Number of Duplicates in Data is {df_copy.duplicated().sum()}")
df_copy.drop_duplicates(inplace=True)
print(f"\nThe number of Duplicates after Dropping is {df_copy.duplicated().sum()}")

Number of Duplicates in Data is 8

The number of Duplicates after Dropping is 0

# **Data Preperation**

In [58]:
X = df_copy[['study_hours_per_day','attendance_percent','sleep_hours','previous_score','has_tuition','assignments_completed']]
y = df_copy['exam_score']

print("The Shape of X is ",X.shape)
print("The Shape of y is ",y.shape)

The Shape of X is  (520, 6)
The Shape of y is  (520,)

In [67]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.6,random_state=42)

print(f'The Size of training data is {X_train.shape} and {y_train.shape}')
print(f'\nThe Size of Testing data is {X_test.shape} and {y_test.shape}\n')
print(f"The number of NaN Values in training data is:- \n{X_train.isna().sum() + y_train.isna().sum()}\n")
print(f"The number of NaN Values in testing data is:- \n{X_test.isna().sum() + y_test.isna().sum()}")

The Size of training data is (312, 6) and (312,)

The Size of Testing data is (208, 6) and (208,)

The number of NaN Values in training data is:-
study_hours_per_day      0
attendance_percent       0
sleep_hours              0
previous_score           0
has_tuition              0
assignments_completed    0
dtype: int64

The number of NaN Values in testing data is:-
study_hours_per_day      0
attendance_percent       0
sleep_hours              0
previous_score           0
has_tuition              0
assignments_completed    0
dtype: int64

# **Model**

## *Train*

In [68]:
model = LinearRegression()
model.fit(X_train,y_train)
print("Model Trained")

Model Trained

## *Training Evaluation*

In [70]:
print(f"Intercept (β₀): {model.intercept_:.4f}\n")
print("Feature Coefficients:")
for feature, coef in zip(X.columns, model.coef_):
    print(f"  {feature:22} → {coef:.4f}")

Intercept (β₀): 33.8820

Feature Coefficients:
  study_hours_per_day    → 2.8262
  attendance_percent     → 0.1831
  sleep_hours            → 0.4073
  previous_score         → 0.3108
  has_tuition            → 3.5619
  assignments_completed  → 0.5337

## *Test*

In [81]:
pred = model.predict(X_test)

comparison = pd.DataFrame({
    "Actual Values" : y_test.values,
    'Pridicted Values' : pred.round(3),
    'Difference': (y_test.values - pred).round(3)
})

print(comparison.head(10))

   Actual Values  Pridicted Values  Difference
0           96.7            88.685       8.015
1           85.3            82.473       2.827
2           99.2            90.553       8.647
3           99.3            89.154      10.146
4          100.0           103.176      -3.176
5           97.1            88.353       8.747
6           81.9            81.166       0.734
7           75.6            80.792      -5.192
8          100.0           109.632      -9.632
9          100.0            96.199       3.801

### *Accuracy*

In [79]:
r2 = r2_score(y_test,pred)
print(f"The Accuracy of the model is {round(r2,4)*100}%")

The Accuracy of the model is 78.91%

### *Test Mectrics*

In [88]:
mae  = mean_absolute_error(y_test, pred)
rmse = np.sqrt(mean_squared_error(y_test, pred))

print(f"On an Average the Model is Off by:  {mae:.3f} Marks")
print(f"RMSE:      {rmse:.4f}")

On an Average the Model is Off by:  4.449 Marks
RMSE:      5.8350

## *Test With your Own Data*

In [90]:
features = ['study_hours_per_day','attendance_percent','sleep_hours','previous_score','has_tuition','assignments_completed']

hour = float(input("How many hours do you Study in a day:- "))
attendance = float(input("Your Attendance %:- "))
Sleep_hours = float(input("How many hours do you Sleep:- "))
Pre_score = float(input("Previous Exam Score:- "))
Tuition = bool(input("Do u go to Tuition(Leave blank if u don't):- "))
assisment = float(input("No of Assisment You have Completed:- "))

user_data = [[hour,attendance,Sleep_hours,Pre_score,Tuition,assisment]]

X_user = pd.DataFrame(user_data,columns=features)

y_user = model.predict(X_user)

print(f"Based on the Provided Data you can score around {y_user.round(2)[0]} Marks")

Based on the Provided Data you can score around 63.28 Marks