# **Import Things**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (confusion_matrix,
                             classification_report,
                             accuracy_score)
print('import Done Boss')

import Done Boss

# **Data Exploration**

## *Load The Data*

In [2]:
file_path = input("Enter the File Path: ")
df = pd.read_csv(file_path)
print('Data Loaded Boss')

Data Loaded Boss

## *Exploration*

In [3]:
print(f"The Dataset have {df.shape[0]} Rows and {df.shape[1]} Columns with {df.duplicated().sum()} Duplicates")

The Dataset have 32300 Rows and 10 Columns with 298 Duplicates

In [4]:
df.head()

,age,length_of_stay_days,num_diagnoses,num_medications,prev_admissions,glucose_level,bmi,has_diabetes,discharge_type,readmitted_30days
0,22.0,28.0,2.0,13.0,4.0,89.1,48.4,1.0,2.0,0
1,44.0,12.0,7.0,11.0,2.0,254.8,23.9,1.0,0.0,1
2,34.0,15.0,9.0,16.0,6.0,270.2,16.7,0.0,1.0,1
3,39.0,15.0,5.0,16.0,6.0,208.6,18.2,0.0,1.0,1
4,62.0,24.0,1.0,6.0,6.0,233.1,44.0,0.0,0.0,1

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32300 entries, 0 to 32299
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  31653 non-null  str
 1   length_of_stay_days  31652 non-null  float64
 2   num_diagnoses        31655 non-null  float64
 3   num_medications      31654 non-null  float64
 4   prev_admissions      31654 non-null  float64
 5   glucose_level        31654 non-null  float64
 6   bmi                  31654 non-null  float64
 7   has_diabetes         31653 non-null  float64
 8   discharge_type       31655 non-null  float64
 9   readmitted_30days    32300 non-null  int64
dtypes: float64(8), int64(1), str(1)
memory usage: 2.6 MB

In [6]:
df.describe()

,length_of_stay_days,num_diagnoses,num_medications,prev_admissions,glucose_level,bmi,has_diabetes,discharge_type,readmitted_30days
count,31652.000000,31655.000000,31654.00000,31654.000000,31654.000000,31654.000000,31653.000000,31655.000000,32300.000000
mean,15.008846,7.529521,10.05418,4.500916,179.799055,32.571947,0.355195,0.998136,0.499659
std,8.394087,4.023350,5.57273,2.865609,69.854520,10.098815,0.478580,0.815959,0.500008
min,1.000000,1.000000,1.00000,0.000000,60.000000,-5.000000,0.000000,0.000000,0.000000
25%,8.000000,4.000000,5.00000,2.000000,119.000000,23.900000,0.000000,0.000000,0.000000
50%,15.000000,8.000000,10.00000,5.000000,179.900000,32.600000,0.000000,1.000000,0.000000
75%,22.000000,11.000000,15.00000,7.000000,240.700000,41.200000,1.000000,2.000000,1.000000
max,29.000000,14.000000,200.00000,9.000000,900.000000,50.000000,1.000000,2.000000,1.000000

In [7]:
print("NaN values in the columns are: ")
print(df.isna().sum())

NaN values in the columns are:
age                    647
length_of_stay_days    648
num_diagnoses          645
num_medications        646
prev_admissions        646
glucose_level          646
bmi                    646
has_diabetes           647
discharge_type         645
readmitted_30days        0
dtype: int64