# **Import Libraries**

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from math import floor
from sklearn.metrics import (accuracy_score,
                             classification_report,
                             confusion_matrix)
print("Import Done boss")

Import Done boss

# **Data Exploration**

## *Load the Data*

In [2]:
file_path = input("Enter the File Path: ")
df = pd.read_csv(file_path)
print('Data Loaded Boss')

Data Loaded Boss

## *Exploration*

In [3]:
print(f"The dataset have {df.shape[0]} Rows and {df.shape[1]} columns with {df.duplicated().sum()} duplicates")

The dataset have 32300 Rows and 10 columns with 299 duplicates

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32300 entries, 0 to 32299
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   session_duration_min  31655 non-null  str
 1   pages_viewed          31655 non-null  float64
 2   cart_value            31654 non-null  float64
 3   prev_purchases        31653 non-null  float64
 4   discount_percent      31654 non-null  float64
 5   device_type           31655 non-null  float64
 6   day_of_week           31657 non-null  float64
 7   bounce_rate           31654 non-null  float64
 8   loyalty_score         31649 non-null  float64
 9   made_purchase         32300 non-null  int64
dtypes: float64(8), int64(1), str(1)
memory usage: 2.6 MB

In [5]:
df.head()

,session_duration_min,pages_viewed,cart_value,prev_purchases,discount_percent,device_type,day_of_week,bounce_rate,loyalty_score,made_purchase
0,67.0,36.0,2632.33,8.0,42.8,2.0,6.0,0.691,76.0,1
1,87.0,45.0,655.80,5.0,8.6,0.0,6.0,0.424,69.0,0
2,115.0,42.0,3419.47,1.0,7.1,NaN,4.0,0.090,84.0,1
3,90.0,23.0,3593.45,1.0,35.4,0.0,6.0,0.322,27.0,0
4,67.0,42.0,1454.89,18.0,13.3,1.0,2.0,0.691,3.0,0

In [6]:
df.describe()

,pages_viewed,cart_value,prev_purchases,discount_percent,device_type,day_of_week,bounce_rate,loyalty_score,made_purchase
count,31655.000000,31654.000000,31653.000000,31654.000000,31655.000000,31657.000000,31654.000000,31649.000000,32300.000000
mean,25.144085,2513.634048,9.475437,25.145587,0.992545,2.990966,0.502242,49.112768,0.503839
std,14.076242,1440.054270,5.768974,14.438897,0.816798,2.001558,0.290431,28.768134,0.499993
min,1.000000,-200.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,13.000000,1271.957500,4.000000,12.600000,0.000000,1.000000,0.252000,24.000000,0.000000
50%,25.000000,2523.595000,9.000000,25.300000,1.000000,3.000000,0.501000,49.000000,1.000000
75%,37.000000,3764.992500,14.000000,37.600000,2.000000,5.000000,0.754000,74.000000,1.000000
max,49.000000,4999.600000,19.000000,150.000000,2.000000,6.000000,5.000000,200.000000,1.000000

In [7]:
print("NaN values in the dataset is: ")
print(df.isna().sum())

NaN values in the dataset is:
session_duration_min    645
pages_viewed            645
cart_value              646
prev_purchases          647
discount_percent        646
device_type             645
day_of_week             643
bounce_rate             646
loyalty_score           651
made_purchase             0
dtype: int64

# **Data Cleaning**

## **Create Copy**

In [18]:
df_copy = df.copy()
print("Copy created boss")

Copy created boss

## **Datatype**

In [19]:
df_copy['session_duration_min'] = df_copy['session_duration_min'].replace('_err','',regex=True).astype('float')

## **Impossible values**

In [20]:
df_copy.loc[df_copy['session_duration_min']<=0,'session_duration_min'] = np.nan

df_copy.loc[df_copy['cart_value']<0,'cart_value'] = np.nan

df_copy.loc[df_copy['discount_percent']>50,'discount_percent'] = np.nan

df_copy.loc[df_copy['bounce_rate']>1,'bounce_rate'] = np.nan

df_copy.loc[df_copy['loyalty_score']>100,'loyalty_score'] = np.nan

## **Dulpicates**

In [23]:
print("Dateset have duplicates: ")
print(f"Before: {df_copy.duplicated().sum()}")
df_copy.drop_duplicates(inplace=True)
print(f"After: {df_copy.duplicated().sum()}")

Dateset have duplicates:
Before: 300
After: 0

## **NaN Values**

### *Fill Them*

In [25]:
print("NaN values in the Dataset is: ")
print(df_copy.isna().sum())
NaN_columns = df_copy.columns.tolist()
NaN_columns.remove('made_purchase')
for col in NaN_columns:
    df_copy[col] = df_copy[col].fillna(floor(df_copy[col].median()))
print("NaN values in the Dataset after filling is: ")
print(df_copy.isna().sum())

NaN values in the Dataset is:
session_duration_min    641
pages_viewed            640
cart_value              641
prev_purchases          640
discount_percent        641
device_type             640
day_of_week             640
bounce_rate             641
loyalty_score           641
made_purchase             0
dtype: int64
NaN values in the Dataset after filling is:
session_duration_min    0
pages_viewed            0
cart_value              0
prev_purchases          0
discount_percent        0
device_type             0
day_of_week             0
bounce_rate             0
loyalty_score           0
made_purchase           0
dtype: int64

### *Drop them*

In [ ]:
print("NaN values in the Dataset is: ")
print(df_copy.isna().sum())
df_copy.dropna(inplace=True)
print("NaN values in the Dataset after filling is: ")
print(df_copy.isna().sum())