# **Import Libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (accuracy_score,
                             precision_score,
                             recall_score,
                             classification_report,
                             f1_score,
                             confusion_matrix)

print("Libraries Loaded✅")

Libraries Loaded✅

# **Data Exploration**

## *LOAD THE DATA*

In [2]:
df = pd.read_csv("C:\\Users\\abhay\\OneDrive\\Desktop\\ML learning\\Logistic Regression\\Disease Diagonos\\Data\\disease_diagnosis.csv")
print('Data Loaded👍')

Data Loaded👍

## *EXPLORATION*

In [3]:
print(f"The Shape of dataset: {df.shape}")

The Shape of dataset: (634, 8)

In [4]:
print("First 5 Rows")
df.head()

First 5 Rows

,age,bmi,blood_sugar,blood_pressure,cholesterol,is_smoker,family_history,has_disease
0,50.0,42.2,117.1,102.0,227.0,0.0,0.0,1
1,42.0,27.9,111.7,82.0,142.0,0.0,0.0,0
2,56.0,31.2,73.2,136.0,181.0,1.0,0.0,1
3,38.0,29.8,247.5,123.0,132.0,0.0,1.0,1
4,71.0,29.0,271.3,68.0,256.0,1.0,1.0,1

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 634 entries, 0 to 633
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             634 non-null    float64
 1   bmi             634 non-null    str
 2   blood_sugar     614 non-null    float64
 3   blood_pressure  634 non-null    float64
 4   cholesterol     613 non-null    float64
 5   is_smoker       634 non-null    float64
 6   family_history  634 non-null    float64
 7   has_disease     634 non-null    int64
dtypes: float64(6), int64(1), str(1)
memory usage: 39.8 KB

In [6]:
df.describe()

,age,blood_sugar,blood_pressure,cholesterol,is_smoker,family_history,has_disease
count,634.000000,614.000000,634.000000,613.000000,634.000000,634.000000,634.000000
mean,51.790221,188.406515,97.981073,218.185971,0.351735,0.370662,0.802839
std,16.295606,71.793044,23.165036,58.519574,0.477889,0.483364,0.398169
min,25.000000,71.300000,-20.000000,120.000000,0.000000,0.000000,0.000000
25%,38.000000,131.875000,79.000000,167.000000,0.000000,0.000000,1.000000
50%,51.000000,189.350000,97.000000,220.000000,0.000000,0.000000,1.000000
75%,65.000000,243.925000,117.000000,268.000000,1.000000,1.000000,1.000000
max,150.000000,900.000000,139.000000,318.000000,1.000000,1.000000,1.000000

In [12]:
print(f"The NaN Values in the Data is: {df.isna().sum()}")

The NaN Values in the Data is: age                0
bmi                0
blood_sugar       20
blood_pressure     0
cholesterol       21
is_smoker          0
family_history     0
has_disease        0
dtype: int64

In [13]:
print(f"The Duplicates Values in the Data is: {df.duplicated().sum()}")

The Duplicates Values in the Data is: 14