# **Import the libraries**

In [3]:
import pandas as pd          
import numpy as np           
from sklearn.linear_model import LinearRegression   
from sklearn.model_selection import train_test_split 
from sklearn.metrics import mean_absolute_error      
from sklearn.metrics import r2_score                 
from sklearn.metrics import mean_squared_error       
import matplotlib.pyplot as plt  
import seaborn as sns             
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)
print("All libraries loaded successfully ✅")

All libraries loaded successfully ✅

# **Data Exploration**

## *Load The Data*

In [5]:
df = pd.read_csv("C:\\Users\\abhay\\OneDrive\\Desktop\\ML learning\\Linear Regression\\Practice\\House Price\\Data\\house_price.csv")

## *Exploration*

In [9]:
print(f"The Data Shape is {df.shape}")

The Data Shape is (612, 7)

In [ ]:
# First 5 Rows
df.head()

,area_sqft,bedrooms,age_years,distance_to_metro_km,floor_number,has_parking,price_lakh
0,3674.0,2.0,5.0,NaN,4.0,0.0,167.31
1,1360.0,3.0,26.0,NaN,16.0,1.0,67.86
2,1794.0,3.0,39.0,12.7,18.0,1.0,81.65
3,1630.0,4.0,33.0,19.1,18.0,1.0,80.48
4,1595.0,3.0,11.0,5.3,11.0,1.0,106.39

In [11]:
# Last 5 rows
df.tail()

,area_sqft,bedrooms,age_years,distance_to_metro_km,floor_number,has_parking,price_lakh
607,2565.0,3.0,33.0,4.1,8.0,1.0,118.48
608,2568.0,4.0,11.0,12.2,13.0,0.0,145.71
609,1297.0,4.0,17.0,12.0,18.0,0.0,79.49
610,2561.0,4.0,23.0,19.6,11.0,1.0,119.91
611,2979.0,3.0,0.0,27.2,14.0,1.0,138.29

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 612 entries, 0 to 611
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   area_sqft             592 non-null    float64
 1   bedrooms              612 non-null    float64
 2   age_years             612 non-null    float64
 3   distance_to_metro_km  597 non-null    float64
 4   floor_number          612 non-null    float64
 5   has_parking           612 non-null    float64
 6   price_lakh            612 non-null    float64
dtypes: float64(7)
memory usage: 33.6 KB

In [13]:
df.describe()

,area_sqft,bedrooms,age_years,distance_to_metro_km,floor_number,has_parking,price_lakh
count,592.000000,612.000000,612.000000,597.000000,612.000000,612.000000,612.000000
mean,2299.028716,2.792484,20.001634,17.741541,9.563725,0.686275,120.287190
std,1000.344347,1.030346,11.519499,9.693690,5.868236,0.464386,395.045922
min,0.000000,1.000000,-3.000000,1.000000,0.000000,0.000000,10.000000
25%,1474.250000,2.000000,10.750000,9.000000,4.000000,0.000000,66.317500
50%,2270.500000,3.000000,19.500000,18.000000,10.000000,1.000000,106.545000
75%,3196.500000,4.000000,30.000000,26.200000,15.000000,1.000000,144.862500
max,3999.000000,5.000000,39.000000,34.800000,19.000000,1.000000,9800.000000

## *Nulls & Duplicates*

In [ ]:
print("The NaN % the Data have is ")
print()
NaN = df.isna().sum()
print({round((NaN/len(df))*100,2)})

The NaN % the Data have is

area_sqft               3.27
bedrooms                0.00
age_years               0.00
distance_to_metro_km    2.45
floor_number            0.00
has_parking             0.00
price_lakh              0.00
dtype: float64%

In [21]:
print(f"The Total Duplicates the Dataset have: {df.duplicated().sum()}")

The Total Duplicates the Dataset have: 12

# **Data Cleaning**